
package dominio;

/**
 *
 * @author wilqu
 */
public class JanelaAcesso extends javax.swing.JFrame {

    private String usuario1;
    private String usuario2;
   
    public JanelaAcesso(String usuario1, String usuario2) {
        this.usuario1 =  usuario1;
        this.usuario2 =  usuario2;
        
        initComponents();
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        titulo = new javax.swing.JLabel();
        jogado1 = new javax.swing.JLabel();
        jogador2 = new javax.swing.JLabel();
        nomeJogador1 = new javax.swing.JTextField();
        nomeJogador2 = new javax.swing.JTextField();
        jSeparator1 = new javax.swing.JSeparator();
        jSeparator2 = new javax.swing.JSeparator();
        imagVelho = new javax.swing.JLabel();
        acessar = new javax.swing.JButton();
        recebeJogador1 = new javax.swing.JLabel();
        recebeJogador1.setVisible(false);
        recebeJogador2 = new javax.swing.JLabel();
        jogar = new javax.swing.JButton();
        imgbola = new javax.swing.JLabel();
        imgZ = new javax.swing.JLabel();
        tabuleiro = new javax.swing.JLabel();
        mostrarNomeJogador1 = new javax.swing.JLabel();
        mostrarNomeJogador2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        titulo.setFont(new java.awt.Font("Arial", 0, 32)); // NOI18N
        titulo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        titulo.setText("Jogo da Velha");
        jPanel1.add(titulo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 598, 49));

        jogado1.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        jogado1.setText("Jogador 1");
        jPanel1.add(jogado1, new org.netbeans.lib.awtextra.AbsoluteConstraints(51, 73, -1, 35));

        jogador2.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        jogador2.setText("Jogador 2");
        jPanel1.add(jogador2, new org.netbeans.lib.awtextra.AbsoluteConstraints(51, 115, -1, 35));

        nomeJogador1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nomeJogador1ActionPerformed(evt);
            }
        });
        jPanel1.add(nomeJogador1, new org.netbeans.lib.awtextra.AbsoluteConstraints(143, 76, 293, 30));
        jPanel1.add(nomeJogador2, new org.netbeans.lib.awtextra.AbsoluteConstraints(143, 118, 293, 30));
        jPanel1.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 56, 598, 10));
        jPanel1.add(jSeparator2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 195, 598, -1));

        imagVelho.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagem/fundodovelho.png"))); // NOI18N
        jPanel1.add(imagVelho, new org.netbeans.lib.awtextra.AbsoluteConstraints(263, 204, 335, -1));

        acessar.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        acessar.setText("Acessar");
        acessar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                acessarActionPerformed(evt);
            }
        });
        jPanel1.add(acessar, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 157, -1, -1));

        recebeJogador1.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        recebeJogador1.setText("Jogador 1 comeca com:");
        jPanel1.add(recebeJogador1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 220, 160, 20));

        recebeJogador2.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        recebeJogador2.setText("Jogador 2 comeca com :");
        recebeJogador2.setVisible(false);
        jPanel1.add(recebeJogador2, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 307, -1, 30));

        jogar.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        jogar.setText("Iniciar Jogo");
        jogar.setVisible(false);
        jogar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jogarActionPerformed(evt);
            }
        });
        jPanel1.add(jogar, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 400, 130, 30));

        imgbola.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        imgbola.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagem/o_icone.png"))); // NOI18N
        imgbola.setVisible(false);
        jPanel1.add(imgbola, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 210, 50, 40));

        imgZ.setVisible(false);
        imgZ.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        imgZ.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagem/z_icone.png"))); // NOI18N
        jPanel1.add(imgZ, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 300, -1, 40));

        tabuleiro.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        tabuleiro.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagem/JogodaVelha.gif"))); // NOI18N
        jPanel1.add(tabuleiro, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 200, 260, 250));

        mostrarNomeJogador1.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        mostrarNomeJogador1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jPanel1.add(mostrarNomeJogador1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 260, 110, 30));

        mostrarNomeJogador2.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        mostrarNomeJogador2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jPanel1.add(mostrarNomeJogador2, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 350, 110, 30));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void nomeJogador1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nomeJogador1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_nomeJogador1ActionPerformed

    private void acessarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_acessarActionPerformed
      acessar.setVisible(false);
      tabuleiro.setVisible(false);
      imgbola.setVisible(true);
      imgZ.setVisible(true);
      mostrarNomeJogador1.setVisible(true);
      mostrarNomeJogador2.setVisible(true);
      recebeJogador1.setVisible(true);
      recebeJogador2.setVisible(true);
      jogar.setVisible(true);
      
      
      usuario1 =  nomeJogador1.getText();
      usuario2 =  nomeJogador2.getText();
      
      mostrarNomeJogador1.setText(usuario1);
      mostrarNomeJogador2.setText(usuario2);
       
       acessar.setVisible(false);     
       
       
        
    }//GEN-LAST:event_acessarActionPerformed

    private void jogarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jogarActionPerformed
        
       JanelaJogar pp = new JanelaJogar(usuario1, usuario2);
       pp.setVisible(true);
       dispose();
    }//GEN-LAST:event_jogarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(JanelaAcesso.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(JanelaAcesso.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(JanelaAcesso.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JanelaAcesso.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new JanelaAcesso(null, null).setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton acessar;
    private javax.swing.JLabel imagVelho;
    private javax.swing.JLabel imgZ;
    private javax.swing.JLabel imgbola;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JLabel jogado1;
    private javax.swing.JLabel jogador2;
    private javax.swing.JButton jogar;
    private javax.swing.JLabel mostrarNomeJogador1;
    private javax.swing.JLabel mostrarNomeJogador2;
    private javax.swing.JTextField nomeJogador1;
    private javax.swing.JTextField nomeJogador2;
    private javax.swing.JLabel recebeJogador1;
    private javax.swing.JLabel recebeJogador2;
    private javax.swing.JLabel tabuleiro;
    private javax.swing.JLabel titulo;
    // End of variables declaration//GEN-END:variables
}
